mplayer/mplayer/main/routes.py
from flask import render_template, request, Blueprint, url_for
from flask_login import current_user

main = Blueprint('main', __name__)


posts =[]
@main.route("/")
@main.route("/home")
def home():
    if current_user.is_authenticated:
        image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
        return render_template('home.html', posts=posts, image_file=image_file)
    else:
        return render_template('home.html', posts=posts)  
 

mplayer/mplayer/music/routes.py
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_required, current_user
from mplayer import db, bcrypt
from ytmusicapi import YTMusic
from mplayer.music.vlcpl import *
from mplayer.users.forms import SearchForm
from mplayer.models import sng_in_pl

music = Blueprint('music', __name__)
ytmusic = YTMusic()
player = playerwrapper()

@music.route('/browse/<song_ID>/<title>/<duration>/<artist>/<thumbnail>', methods=['GET', 'POST'])
def play_song(song_ID, title, duration, artist, thumbnail):
    thumbnail = 'https://lh3.googleusercontent.com/'+thumbnail
    print(thumbnail)
    return render_template('play_song.html', song_ID = song_ID, title=title, duration=duration, artist=artist, thumbnail=thumbnail)

@music.route('/play_song_process')
def play_song_process():
    try:
        song_ID = request.args.get('song_ID', 0, type=str)
        print('Playing ' + song_ID)
        song_url = 'song://' + song_ID
        player.setPlaylist(song_url)
        player.playPlaylist()
        return jsonify(result='You are playing ' + song_ID)

    except Exception as e:
        return str(e)

@music.route('/pause_song_process')
def pause_song_process():
    try:
        song_ID = request.args.get('song_ID', 0, type=str)
        print('Paused ' + song_ID)
        player.pausePlaylist()
        return jsonify(result='Paused ' + song_ID)

    except Exception as e:
        return str(e)
        
@music.route('/stop_song_process')
def stop_song_process():
    try:
        song_ID = request.args.get('song_ID', 0, type=str)
        print('Stopped ' + song_ID)
        player.stopPlaylist()
        return jsonify(result='Stopped ' + song_ID)

    except Exception as e:
        return str(e)

@music.route('/browse', methods=['POST', 'GET'])
def browse():
    form = SearchForm()
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    if form.validate_on_submit():
        try:
            song_name = list(str(form.song_name))
            song_name = song_name[67:]
            song_name = song_name[0:-2]
            song_name = ''.join(song_name)
            song_results = ytmusic.search(query = song_name, filter = "songs")
            song_ID = song_results[0]['videoId']
            title = song_results[0]['title']
            duration=song_results[0]['duration']
            artist = song_results[0]['artists'][0]['name']
            thumbnail=song_results[0]['thumbnails'][0]['url']
            thumbnail=list(thumbnail)
            thumbnail=thumbnail[34:]
            thumbnail=''.join(thumbnail)
            return redirect(url_for('music.play_song', song_ID= song_ID,  title=title, duration=duration, artist=artist, thumbnail=thumbnail ))
        except Exception as e:
            return str(e)

    return render_template('browse.html', form=form, image_file=image_file)

'''@music.route('/background_process')
def background_process():
    try:
        song_name = request.args.get('song_name', 0, type=str)
        song_results = ytmusic.search(query = song_name, filter = "songs")
        song_ID = song_results[0]['videoId']
        return jsonify(result='You added ' + song_ID)

    except Exception as e:
        return str(e)'''

@login_required
@music.route('/playlist_play')
def playlist_play():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        playlist_url = 'playlist://' + playlist_name
        player.setPlaylist(playlist_url)
        player.playPlaylist()
        return jsonify(result='Playing ' + playlist_name)

    except Exception as e:
        return str(e)


@music.route('/playlist_pause')
def playlist_pause():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.pausePlaylist()
        return jsonify(result='Pausing ' + playlist_name)

    except Exception as e:
        return str(e)

@music.route('/playlist_next')
def playlist_next():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.nextInPlaylist()
        return jsonify(result='Playing next song in ' + playlist_name)

    except Exception as e:
        return str(e)

@music.route('/playlist_previous')
def playlist_previous():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.previousInPlaylist()
        return jsonify(result='Playing previous song in ' + playlist_name)

    except Exception as e:
        return str(e)

@music.route('/playlist_repeat')
def playlist_repeat():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.setPlaybackMode('repeat')
        return jsonify(result='Setting playback mode to repeating current song')

    except Exception as e:
        return str(e)

@music.route('/playlist_loop')
def playlist_loop():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.setPlaybackMode('loop')
        return jsonify(result='Setting playback mode to looping current playlist')

    except Exception as e:
        return str(e)

@music.route('/playlist_default')
def playlist_default():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.setPlaybackMode('default')
        return jsonify(result='Restoring to default sequential playback mode')

    except Exception as e:
        return str(e)

@music.route('/playlist_stop')
def playlist_stop():
    try:
        playlist_name = request.args.get('playlist_name', '0', type=str)
        player.stopPlaylist()
        return jsonify(result='Stopping ' + playlist_name)

    except Exception as e:
        return str(e)

#playlist choices
@login_required
@music.route('/playlist')
def playlist():
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('playlist.html', image_file = image_file)

@music.route('/choice1', methods=['POST', 'GET'])
def choice1():
    try:
        song_pl = request.args.get('song_name', 0, type=str)
        lst = song_pl.split("_")
        sng = lst[0]
        pl = lst[1]#we actually have to add song id

        song_results = ytmusic.search(query = sng, filter = "songs")
        song_ID = song_results[0]['videoId']
        songinfo = sng_in_pl(username=current_user.username, playlist=pl, song=song_ID)
        db.session.add(songinfo)
        db.session.commit()
        return jsonify(result='You added ' + sng + 'in' + pl)

    except SQLAlchemyError as e:
        err = str(e.__dict__['orig'])
        print(err)
        return err
    except Exception as e:
        return str(e)

@music.route('/choice2', methods=['POST', 'GET'])
def choice2():
    try:
        song_pl = request.args.get('song_name', 0, type=str)
        lst = song_pl.split("_")
        sng = lst[0]
        pl = lst[1]#we actually have to add song id

        song_results = ytmusic.search(query = sng, filter = "songs")
        song_ID = song_results[0]['videoId']
        songinfo = sng_in_pl(username=current_user.username, playlist=pl, song=song_ID)
        db.session.delete(songinfo)
        db.session.commit()
        return jsonify(result='You added ' + sng + 'in' + pl)
    except SQLAlchemyError as e:
        err = str(e.__dict__['orig'])
        print(err)
        return err
    except Exception as e:
        return str(e)

@music.route('/choice3')
def choice3():
    try:
        db.sng_in_pl.filter_by(username=current_user.username)
        return jsonify(result='You added ' + sng + 'in' + pl)

    except Exception as e:
        return str(e)

@music.route('/choice4', methods=['POST', 'GET'])
def choice4():
    try:
        pl = request.args.get('song_name', 0, type=str)
        fil = db.sng_in_pl.filter_by(username=current_user.username)
        fil2 = fil.filter_by(playlist= pl)
        ls = []
        for i in fil2:
            ls.append(i.username)
        return jsonify(result= ls)

    except Exception as e:
        return str(e)

mplayer/mplayer/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from mplayer import db, bcrypt
from mplayer.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, 
                           RequestResetPasswordForm, ResetPasswordForm, DeleteAccountForm)
from mplayer.models import User
from mplayer.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

count = 0

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    global count   
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) 
    if(count == 1):
        flash('Your account has been updated', 'success')
        count = 0
    return render_template('account.html', title='Account', image_file=image_file)

@users.route("/updateaccount", methods=['GET', 'POST'])
@login_required
def updateaccount(): 
    global count
    count = 1   
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))
    elif(request.method == 'GET'):
        form.username.data = current_user.username
        form.email.data = current_user.email    
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('updateaccount.html', title='Update Account info',
                           image_file=image_file, form=form)    
  
@users.route("/deleteaccount", methods=['GET', 'POST'])
@login_required
def delete(): 
    form = DeleteAccountForm()
    if form.validate_on_submit():
        obj = User.query.get(current_user.id)
        db.session.delete(obj)
        db.session.commit()
        flash('Your account has been deleted', 'success')
        return redirect(url_for('main.home'))
    
    return render_template('delete_account.html', title='Delete account', form=form)



@users.route("/reset_password", methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)
  
@users.route("/player", methods=['GET', 'POST'])
def player():
    return render_template('player.html')

mplayer/mplayer/templates/browse.html
{% extends "layout.html" %}
{% block content %}
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type=text/javascript>
        $(function() {
        $('a#process_input').bind('click', function() {
            $.getJSON('/background_process', {
            song_name: $('input[name="song_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
    <!--<script type=text/javascript>
        $(function() {
        $('a#playlist_play').bind('click', function() {
            $.getJSON('/playlist_play', {
            playlist_name: $('input[name="playlist_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
    <script type=text/javascript>
        $(function() {
        $('a#playlist_pause').bind('click', function() {
            $.getJSON('/playlist_pause', {
            playlist_name: $('input[name="playlist_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
    <script type=text/javascript>
        $(function() {
        $('a#playlist_next').bind('click', function() {
            $.getJSON('/playlist_next', {
            playlist_name: $('input[name="playlist_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
    <script type=text/javascript>
        $(function() {
        $('a#playlist_previous').bind('click', function() {
            $.getJSON('/playlist_previous', {
            playlist_name: $('input[name="playlist_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
    <script type=text/javascript>
        $(function() {
        $('a#playlist_stop').bind('click', function() {
            $.getJSON('/playlist_stop', {
            playlist_name: $('input[name="playlist_name"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>-->
</head>

<body>
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">  <!-- Encryption type-->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend>Search</legend>
                <hr style="width:50%;text-align: left; margin-left:0; margin-top: 0">
                <div class="form-group">
                    {{ form.song_name.label(class="form-control-label") }}
    
                    {% if form.song_name.errors %}
                        {{ form.song_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.song_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.song_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        <!--<form>
            <input type=text size=5 name=playlist_name>
            <a href=# id=playlist_play><button class='btn btn-default'>Play</button></a>
            <a href=# id=playlist_pause><button class='btn btn-default'>Pause</button></a>
            <a href=# id=playlist_next><button class='btn btn-default'>Next</button></a>
            <a href=# id=playlist_previous><button class='btn btn-default'>Previous</button></a>
            <a href=# id=playlist_stop><button class='btn btn-default'>Stop</button></a>
        </form>-->
    <p id=result></p>
    </div>
</body>
{% endblock content %}

mplayer/mplayer/templates/choice1.html
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type=text/javascript>
        $(function() {
        $('a#process_input').bind('click', function() {
            $.getJSON('/choice1', {
            playlist_name: $('input[name="getsminput"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
</head>

<body>
    <div class='container'>
    <h3>Musico player</h3>
        <form>
            <input type=text name=getsminput>
            <a href=# id=process_input><button class='btn btn-default'>Add</button></a>
        </form>
    <p id=result></p>
    </div>
</body>

mplayer/mplayer/templates/choice2.html
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type=text/javascript>
        $(function() {
        $('a#process_input').bind('click', function() {
            $.getJSON('/choice2', {
            getsminput: $('input[name="getsminput"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
</head>

<body>
    <div class='container'>
    <h3>Musico player</h3>
        <form>
            <input type=text name=getsminut>
            <a href=# id=process_input><button class='btn btn-default'>Add</button></a>
        </form>
    <p id=result></p>
    </div>
</body>

mplayer/mplayer/templates/choice3.html
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type=text/javascript>
        $(function() {
        $('a#process_input').bind('click', function() {
            $.getJSON('/choice3', {
            getsminput: $('input[name="getsminput"]').val(),
            }, function(data) {
            $("#result").text(data.result);
            });
            return false;
        });
        });
    </script>
</head>

<body>
    <div class='container'>
    <h3>Musico player</h3>
        <form>
            <input type=text name=getsminut>
            <a href=# id=process_input><button class='btn btn-default'>Add</button></a>
        </form>
    <p id=result></p>
    </div>
</body>

mplayer/mplayer/templates/delete_account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">  <!-- Encryption type-->
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend>Delete Account</legend>
            <hr style="width:50%;text-align: left; margin-left:0; margin-top: 0">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                    <div class="{{ category }}">{{ message }}</div>
            {% endfor %}
            {% endwith %} 
            <div class="form-group">
                {{ form.reason.label(class="form-control-label") }}

                {% if form.reason.errors %}
                    {{ form.reason(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.reason(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </div>
</div>    
{% endblock content %}

mplayer/mplayer/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <title>Musico</title>
    <!-- icon for the website-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    
 

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top">
        <div class="container">
          <image src="{{url_for('static',filename = 'favicon.ico')}}" width="35" height="35"></image>
          <a class="navbar-brand mr-4" href="/">Musico</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <!-- vertical seperator-->
              <style>
                .vl {
                  border-left: 2px solid white;
                  height: 18px;
                  align-self: center;      
                }
                </style>
                {% if current_user.is_authenticated %}
                <div class="vl"></div>
                <a class="nav-item nav-link" href="{{ url_for('music.browse') }}">Browse</a>
                {% endif %}
              {% if current_user.is_authenticated %}
              <div class="vl"></div>
                <a class="nav-item nav-link" href="{{ url_for('music.playlist') }}">Playlist</a>
                {% endif %}
            </div>
            <!-- Right corner -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
              <div class="vl"></div>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">LOG IN</a>
                <div class="vl"></div>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">SIGN UP</a>
              {% endif %}  
              {% if current_user.is_authenticated %}
              <div class="media">
                <img class="rounded-circle" src="{{ image_file }}" width="35" height="35"></img>
              </div>
              {% endif %}  
              </main>    
            </div>
          </div>
        </div>
      </nav>
      <main role="main" class="container">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
    </header>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mplayer/mplayer/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="bottom-top mt-5">Log In</legend>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% for category, message in messages %}
                        <div class="{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endwith %}
                <hr style="width:50%;text-align: left; margin-left:0; margin-top: 0">    
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.request_reset') }}">Forgot Password?</a>
                </small>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                </small>
            </div>
        </form>
    </div>    
{% endblock content %}

mplayer/mplayer/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% for category, message in messages %}
                    <div class="{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endwith %}
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

mplayer/mplayer/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}